Beginning site
chijikdanila/Calendar pull request #1
Opened 2022-03-12 13:11 UTC by chijikdanila

2022-03-18 21:41 UTC, Nastik1811 requested changes
Your wireframe should illustrate all main functionality and contain html-tags.

2022-04-23 13:14 UTC, Nastik1811 commented
что происходит? :/

2022-04-24 13:21 UTC, Nastik1811 commented
??

2022-04-27 12:10 UTC, chijikdanila commented
Я думал вы не увидите до следующего PR) Сейчас сделал 4 страницы, которые нарисовал в Figma. Только пока без мобильной версии)

2022-04-27 12:11 UTC, chijikdanila commented
Извините, я же его забыл закрыть)))

2022-04-27 16:38 UTC, Nastik1811 commented
До какого следующего? У вас ещё макет не апрувнут, а вы заливаете сюда вёрстку вообще без каких-либо пояснений

2022-04-27 19:14 UTC, chijikdanila commented
Сейчас все сделаю в лучшем виде, не бейте пж)

2022-04-27 19:14 UTC, closed without merging

2022-04-28 09:09 UTC, Nastik1811 commented
Вас попробуй побить. Вы же на пары не ходите