Lab3
chijikdanila/Calendar pull request #3
Opened 2022-04-29 12:58 UTC by chijikdanila

HTML + CSS. 3я лабораторная.

Ссылка на деплой: http://www.itirod-site.zzz.com.ua

Из браузеров лучше использовать Chrome) В Opera заметил некорректное отображение страницы добавления ивента, а в Chrome с ней всё нормально.

Мобильную версию делал под Pixel 5. (393x851)

Переход по страницам осуществляется по кнопкам, также вверху слева будет кнопка возвращения не предыдущую страницы (к 4ой лабораторной её уже не будет)

2022-05-04 12:17 UTC, Nastik1811 requested changes
Как минимум, поменяйте label'ы на подходящие теги, добавьте form для формы создания нового события, добавьте label'ам в форме атрибут for. Поставлю `7`

И почему 2010 год?

2022-05-04 12:17 UTC, nastik1811 commented on css/calendar.css
> +    padding: 1% 1% 1% 1%;
` padding: 1%;` делает то же самое

2022-05-04 12:17 UTC, Nastik1811 commented on index.html
> +                        <p class="registration">Registration</p>
Это к чему?

2022-05-04 12:17 UTC, Nastik1811 commented on index.html
> +                        <p class="registration">Registration</p>
Это к чему?

2022-05-04 12:17 UTC, Nastik1811 commented on index.html
> +                <label class="yearCreation">2022</label>
Это не label

2022-05-04 12:17 UTC, Nastik1811 commented on index.html
> +                <label class="yearCreation">2022</label>
Это не label

2022-05-04 12:17 UTC, Nastik1811 commented on index.html
> +                        <label class="showCurrentTime"></label>
https://www.w3schools.com/tags/tag_label.asp

2022-05-04 12:17 UTC, Nastik1811 commented on index.html
> +                        <label class="showCurrentTime"></label>
https://www.w3schools.com/tags/tag_label.asp

2022-05-04 12:17 UTC, Nastik1811 commented on index.html
> +                <!--Add new event/Change existing event-->
Потеряли `form`

2022-05-04 12:17 UTC, Nastik1811 commented on index.html
> +                <!--Add new event/Change existing event-->
Потеряли `form`

2022-05-04 12:17 UTC, Nastik1811 commented on js/index.js
> +  document.querySelector(".button").style.width = "50%";
не самое элегантное решение, мягко говоря

2022-05-04 12:17 UTC, Nastik1811 commented on js/index.js
> +  document.querySelector(".button").style.width = "50%";
не самое элегантное решение, мягко говоря

2022-05-04 12:17 UTC, Nastik1811 commented on index.html
> +                        <button class="eventsManagement buttonChangePage" value="2">Events management</button>
в следующей лабе это должны быть ссылки, а не кнопки

2022-05-04 12:17 UTC, Nastik1811 commented on index.html
> +                        <button class="eventsManagement buttonChangePage" value="2">Events management</button>
в следующей лабе это должны быть ссылки, а не кнопки

2022-05-05 15:42 UTC, chijikdanila commented
Деплой сделал на https://chijikdanila.github.io/Calendar/ т.к. на старом деплое истёк бесплатный период) Ближе к выходным доделаю правки в 3ей лабе

2022-05-07 11:27 UTC, chijikdanila commented
Учёл все Ваши замечания по 3ей лабе. 

Ещё возник вопрос: в чём разница использования label с атрибутом for отдельно от ввода данных и с вводом данных в самом label?

2022-05-11 11:40 UTC, Nastik1811 approved these changes
Вопрос не совсем поняла
За лабу `6`

2022-05-11 11:40 UTC, nastik1811 commented on css/calendar.css
> +    padding: 1% 1% 1% 1%;
` padding: 1%;` делает то же самое

2022-05-11 11:59 UTC, merged